[package]
edition = "2018"
name = "ra_hir"
version = "0.1.0"
authors = ["rust-analyzer developers"]

[lib]
doctest = false

[dependencies]
log = "0.4.5"
rustc-hash = "1.0"
either = "1.5"

ra_syntax = { path = "../ra_syntax" }
ra_db = { path = "../ra_db" }
hir_expand = { path = "../ra_hir_expand", package = "ra_hir_expand" }
hir_def = { path = "../ra_hir_def", package = "ra_hir_def" }
hir_ty = { path = "../ra_hir_ty", package = "ra_hir_ty" }
